<script setup>
import { computed, onMounted, ref } from 'vue';
const db=useSupabaseClient(), route=useRoute();
const words=ref([]), owned=ref({}), turn=ref(0), question=ref(null), answer=ref(''), die=ref('—'), round=ref(1), done=ref(false), message=ref('載入題庫…');
const players=ref([{name:'你',cash:1500,pos:0},{name:'電腦',cash:1500,pos:0}]);
const me=computed(()=>players.value[turn.value]), owner=id=>owned.value[id]??-1, price=id=>100+Math.floor(words.value.findIndex(w=>w.id===id)/4)*25;
const shuffle=a=>[...a].sort(()=>Math.random()-.5);
function ask(w){question.value={w,type:Math.random()<.5?'meaning':'spell',choices:shuffle([w,...shuffle(words.value.filter(x=>x.id!==w.id)).slice(0,3)])};answer.value='';}
function endTurn(){question.value=null;turn.value=1-turn.value;if(turn.value===0)round.value++;if(round.value>20||players.value.some(p=>p.cash<=0))done.value=true;}
function respond(ok){const w=question.value.w,p=me.value;if(ok&&p.cash>=price(w.id)){owned.value[w.id]=turn.value;p.cash-=price(w.id);message.value=p.name+' 答對並買下 '+w.en_us+'！';}else message.value=ok?'答對了但現金不足。':'答錯了，答案：'+w.en_us+'＝'+w.zh_tw;endTurn();}
function submit(){respond(question.value.type==='meaning'?answer.value===question.value.w.en_us:answer.value.trim().toLowerCase()===question.value.w.en_us.trim().toLowerCase());}
function play(i){if(turn.value!==i||question.value||done.value)return;const n=2+Math.floor(Math.random()*11),p=players.value[i],old=p.pos;die.value=String(n);p.pos=(p.pos+n)%words.value.length;if(p.pos<old)p.cash+=200;const w=words.value[p.pos],o=owner(w.id);if(o>=0){if(o!==i){p.cash-=30;players.value[o].cash+=30;message.value=p.name+' 支付 $30 租金。';}endTurn();return;}question.value={w,type:Math.random()<.5?'meaning':'spell',choices:shuffle([w,...shuffle(words.value.filter(x=>x.id!==w.id)).slice(0,3)])};answer.value='';if(i===1)setTimeout(()=>{if(question.value)respond(Math.random()<.7)},800);}
onMounted(async()=>{let q=db.from('vocabularies').select('id,en_us,zh_tw');for(const k of ['version','volume','unit'])if(route.query[k])q=q.eq(k,route.query[k]);const {data,error}=await q.limit(500);words.value=(data||[]).filter(w=>w.en_us&&w.zh_tw);message.value=error?'題庫載入失敗：'+error.message:words.value.length?'擲骰前進，答對買地、經過起點領 $200。':'找不到單字，請返回選擇單元。';});
</script>
<template><main class="page"><header><NuxtLink to="/">← 返回遊戲選單</NuxtLink><h1>🏘️ 單字大富翁</h1><p>拼字或選中文答題買地，踩到對手土地支付租金。</p></header>
<section class="scores"><div v-for="(p,i) in players" :key="i" :class="{active:turn===i}"><b>{{p.name}}</b><strong>$ {{p.cash}}</strong><span>位置 {{p.pos+1}} · 土地 {{Object.values(owned).filter(x=>x===i).length}}</span></div><div>第 {{round}} / 20 回合 · 骰子 {{die}}</div></section><p class="message">{{message}}</p>
<section v-if="words.length" class="board"><article v-for="(w,i) in words" :key="w.id" class="plot" :class="{you:owner(w.id)===0,cpu:owner(w.id)===1}"><b>{{w.en_us}}</b><span>{{w.zh_tw}}</span><small>地價 {{price(w.id)}} · {{owner(w.id)<0?'待購':players[owner(w.id)].name}}</small><i v-if="players[0].pos===i">🧑‍🎓</i><i v-if="players[1].pos===i">🤖</i></article></section>
<button class="roll" :disabled="turn!==0||!!question||done||!words.length" @click="play(0)">🎲 擲骰前進</button><button v-if="turn===1&&!question&&!done" class="roll cpu" @click="play(1)">▶ 電腦回合</button>
<div v-if="question" class="overlay"><section class="modal"><p>{{me.name}} 踩到無主土地</p><template v-if="question.type==='meaning'"><h2>「{{question.w.en_us}}」的中文意思？</h2><div class="answers"><button v-for="w in question.choices" :key="w.id" @click="answer=w.en_us;submit()">{{w.zh_tw}}</button></div></template><form v-else @submit.prevent="submit"><h2>請拼出：{{question.w.zh_tw}}</h2><input v-model="answer" autofocus placeholder="輸入英文拼字"><button>確認答案</button></form></section></div>
<div v-if="done" class="overlay"><section class="modal"><h1>🏁 {{players[0].cash===players[1].cash?'平手':players[0].cash>players[1].cash?'你贏了！':'電腦獲勝'}}</h1><p>你：{{players[0].cash}} 元　電腦：{{players[1].cash}} 元</p><NuxtLink to="/">回遊戲選單</NuxtLink></section></div></main></template>
<style scoped>
.page{min-height:100vh;padding:22px;background:var(--bg-color,#f4f0e6);color:var(--text-main,#222);box-sizing:border-box}header,.scores,.board,.message{max-width:1000px;margin:0 auto 16px}.scores{display:flex;gap:10px}.scores>div{flex:1;display:grid;gap:5px;padding:12px;border:2px solid #bdc9b9;border-radius:12px;background:white}.scores .active{border-color:#278443}.scores strong{font-size:1.4rem;color:#168342}.board{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:8px;padding:12px;border:5px solid #337447;border-radius:18px;background:#c5e7bd}.plot{min-height:85px;display:grid;align-content:start;gap:4px;padding:8px 4px;border:2px solid #ddd;border-radius:9px;background:#fff;text-align:center;color:#223;overflow-wrap:anywhere}.plot.you{background:#e1f1ff;border-color:#2196f3}.plot.cpu{background:#ffe7e3;border-color:#ef5849}.plot span,.plot small{font-size:.82rem}.plot i{font-style:normal}.roll{display:block;margin:12px auto;padding:13px 26px;border:0;border-radius:10px;background:#71c784;font-size:1.1rem;font-weight:bold}.roll:disabled{opacity:.5}.cpu{background:#ffd180}.message{padding:12px;border-radius:10px;background:white}.overlay{position:fixed;inset:0;z-index:10;display:grid;place-items:center;padding:18px;background:#142117bb}.modal{width:min(480px,100%);padding:26px;border-radius:18px;background:#fff;text-align:center;color:#233}.answers,form{display:grid;gap:9px}.modal button,.modal input{padding:12px;border:2px solid #d3d9d0;border-radius:9px;font-size:1rem}.modal form button{background:#71c784}@media(max-width:650px){.board{grid-template-columns:repeat(3,minmax(0,1fr))}.scores{flex-wrap:wrap}}
</style>